/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PedidoDAO;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pedido;

/**
 *
 * @author Gabriel
 */
public class TelaPedidosCliente extends javax.swing.JFrame {

    private int idCliente;

    /**
     * Creates new form TelaPedidosCliente
     */
   

    public TelaPedidosCliente(int idCliente) {
        initComponents();
        this.idCliente = idCliente;
        carregarPedidosDoCliente(idCliente);
    }

   private void carregarPedidosDoCliente(int idCliente) {
    try {
        PedidoDAO pedidoDAO = new PedidoDAO();
        List<Pedido> listaPedidos = pedidoDAO.listarPedidosPorCliente(idCliente);

        DefaultTableModel modelo = (DefaultTableModel) tabelaPedidos.getModel();
        modelo.setRowCount(0); // Limpa a tabela antes de carregar os dados

        for (Pedido pedido : listaPedidos) {
            String dataFormatada = new SimpleDateFormat("dd/MM/yyyy").format(pedido.getDataPedido());
            modelo.addRow(new Object[]{
                pedido.getIdPedido(),
                dataFormatada,
                pedido.getQuantidade(),
pedido.getValorTotal()
            });
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar pedidos do cliente: " + e.getMessage());
        e.printStackTrace();
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        excluirPedidoSelecionado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEDIDOS");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\IMG_0905 (1).png")); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(453, 453, 453))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID do Pedido", "Data", "Quantidade", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPedidos);

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnDetalhes.setText("DETALHES");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        excluirPedidoSelecionado.setText("EXCLUIR");
        excluirPedidoSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPedidoSelecionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(excluirPedidoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnDetalhes)
                    .addComponent(btnAdicionar)
                    .addComponent(excluirPedidoSelecionado))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed

        int linhaSelecionada = tabelaPedidos.getSelectedRow(); // Obtém a linha selecionada

        if (linhaSelecionada == -1) { // Verifica se uma linha foi selecionada
            JOptionPane.showMessageDialog(this, "Selecione um pedido para ver os detalhes.");
            return; // Sai do método se nenhuma linha foi selecionada
        }

        // Obtém o ID do pedido da linha selecionada
        int idPedido = (int) tabelaPedidos.getValueAt(linhaSelecionada, 0);

        try {
            PedidoDAO pedidoDAO = new PedidoDAO();
            Pedido pedido = pedidoDAO.listarPedidosPorCliente(idCliente).stream()
                    .filter(p -> p.getIdPedido() == idPedido)
                    .findFirst()
                    .orElse(null); // Busca o pedido pelo ID

            if (pedido != null) {
                // Usa o novo construtor com modo de visualização ativado
                TelaComprasCliente tela = new TelaComprasCliente(pedido, true);
                tela.setVisible(true);
                this.dispose(); // Fecha a tela atual, se necessário
            } else {
                JOptionPane.showMessageDialog(this, "Pedido não encontrado.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao buscar os dados do pedido.");
        }


    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        TelaComprasCliente telaCompras = new TelaComprasCliente(idCliente);
        telaCompras.setVisible(true); // Torna a nova tela visível

        // Opcional: Feche a tela atual, se necessário
        this.dispose(); // Fecha a tela atual (opcional)

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
new TelaCadastroCliente().setVisible(true);
        this.dispose();    }//GEN-LAST:event_btnVoltarActionPerformed

    private void excluirPedidoSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPedidoSelecionadoActionPerformed
   int linhaSelecionada = tabelaPedidos.getSelectedRow();

    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um pedido para excluir.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
            "Deseja realmente excluir este pedido e todos os seus produtos?", "Confirmação", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // Pega o ID do pedido da primeira coluna
            int idPedidoSelecionado = (int) tabelaPedidos.getValueAt(linhaSelecionada, 0);

            PedidoDAO pedidoDAO = new PedidoDAO();
            pedidoDAO.excluirPedidoComProdutos(idPedidoSelecionado);

            carregarPedidosDoCliente(idCliente); // Atualiza tabela
            JOptionPane.showMessageDialog(this, "Pedido e seus produtos excluídos com sucesso.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir o pedido: " + ex.getMessage());
            ex.printStackTrace();
        }}
    }//GEN-LAST:event_excluirPedidoSelecionadoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton excluirPedidoSelecionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelaPedidos;
    // End of variables declaration//GEN-END:variables
}
