/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PedidoDAO;
import dao.ProdutoDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import model.Pedido;
import model.Produto;

/**
 *
 * @author Gabriel
 */
public class TelaComprasCliente extends javax.swing.JFrame {

    private int idCliente;
    private int idPedido = -1; // só será definido quando o pedido for criado
    private Pedido pedido;

    // Construtor usado quando o cliente ainda vai adicionar os produtos (modo "adicionar")
    public TelaComprasCliente(int idCliente) {
        initComponents();
        this.idCliente = idCliente;

        try {
            PedidoDAO pedidoDAO = new PedidoDAO();
            this.idPedido = pedidoDAO.criarPedido(idCliente); // Cria o pedido

            if (this.idPedido == -1) {
                throw new SQLException("Erro ao criar pedido: ID inválido.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao criar novo pedido: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Construtor usado quando o pedido já existe (modo "visualização e edição")
    public TelaComprasCliente(int idCliente, Pedido pedido) {
        initComponents();
        this.idCliente = idCliente;
        this.pedido = pedido;
        this.idPedido = pedido.getIdPedido();
        carregarProdutosNaTabela();
    }

    // Construtor para modo somente visualização
    public TelaComprasCliente(Pedido pedido, boolean modoVisualizacao) {
        initComponents();
        this.pedido = pedido;
        this.idCliente = pedido.getIdCliente();
        this.idPedido = pedido.getIdPedido();
        carregarProdutosNaTabela();

        if (modoVisualizacao) {
            desativarCamposDeEdicao();
        }
    }

    private void desativarCamposDeEdicao() {
        txtReferencia.setEnabled(false);
        txtProduto.setEnabled(false);
        txtSuperficie.setEnabled(false);
        txtColecao.setEnabled(false);
        txtFormato.setEnabled(false);
        txtLocalUso.setEnabled(false);
        txtM2Pallet.setEnabled(false);
        txtKgM2.setEnabled(false);
        txtM2Caixa.setEnabled(false);
        txtPcsCaixa.setEnabled(false);
        txtValorPalletizado.setEnabled(false);

        btnSalvar.setEnabled(false);
        btnFinalizar.setEnabled(false);
    }

    private void carregarProdutosNaTabela() {
        if (idPedido == -1) {
            return; // ainda não há pedido criado, então não carrega produtos
        }
        try {
            PedidoDAO pedidoDAO = new PedidoDAO();
            List<Produto> produtos = pedidoDAO.listarProdutosDoPedido(idPedido);

            DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
            modelo.setRowCount(0);

            for (Produto p : produtos) {
                modelo.addRow(new Object[]{
                    p.getReferencia(),
                    p.getProduto(),
                    p.getSuperficie(),
                    p.getColecao(),
                    p.getFormato(),
                    p.getLocalUso(),
                    p.getM2Pallet(),
                    p.getKgM2(),
                    p.getM2Caixa(),
                    p.getPcsCaixa(),
                    p.getValorPalletizado()
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar produtos: " + ex.getMessage());
        }
    }

    private void recarregarTabelaProdutos() {
        carregarProdutosNaTabela();
    }

    // Getter necessário para quando for salvar produto com idPedido
    public int getIdPedido() {
        return this.idPedido;
    }

    // Setter opcional caso precise atribuir idPedido após criação
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSuperficie = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnVoltarCompra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        txtProduto = new javax.swing.JTextField();
        BtnExcluir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLocalUso = new javax.swing.JTextField();
        txtFormato = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtColecao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtM2Caixa = new javax.swing.JTextField();
        txtKgM2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtValorPalletizado = new javax.swing.JTextField();
        txtM2Pallet = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPcsCaixa = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtDataPedido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DETALHES E ADIÇÕES DE PEDIDO");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel\\Downloads\\IMG_0905 (1).png")); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(419, 419, 419)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jLabel2.setText("REFERÊNCIA");

        txtReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReferenciaActionPerformed(evt);
            }
        });

        jLabel3.setText("PRODUTO");

        jLabel4.setText("SUPERFÍCIE");

        txtSuperficie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuperficieActionPerformed(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltarCompra.setText("VOLTAR");
        btnVoltarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCompraActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Referência", "Produto", "Superfície", "Coleção", "Formato", "Local de uso", "M²/Pallet", "KG/M²", "M²/Caixa", "Pçs/Caixa", "Valor Paletizado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        BtnExcluir.setText("EXCLUIR");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel8.setText("FORMATO");

        jLabel9.setText("LOCAL DE USO");

        txtLocalUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalUsoActionPerformed(evt);
            }
        });

        jLabel10.setText("COLEÇÃO");

        txtColecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColecaoActionPerformed(evt);
            }
        });

        jLabel5.setText("KG/M²");

        jLabel6.setText("M²/CAIXA");

        txtM2Caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM2CaixaActionPerformed(evt);
            }
        });

        jLabel11.setText("VALOR ");

        jLabel7.setText("M²/PALLET");

        txtM2Pallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtM2PalletActionPerformed(evt);
            }
        });

        jLabel13.setText("PÇS/CAIXA");

        txtPcsCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPcsCaixaActionPerformed(evt);
            }
        });

        btnFinalizar.setText("FINALIZAR");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        jLabel12.setText("DATA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVoltarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtReferencia)
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLocalUso, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtColecao)
                                .addComponent(txtFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(btnBuscar)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtM2Caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtM2Pallet)
                                .addComponent(txtKgM2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPcsCaixa)
                                .addComponent(txtValorPalletizado, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(99, 99, 99))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnExcluir, btnSalvar, btnVoltarCompra});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtColecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLocalUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtM2Pallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKgM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtM2Caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPcsCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorPalletizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(BtnExcluir)
                    .addComponent(btnVoltarCompra)
                    .addComponent(btnFinalizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnExcluir, btnSalvar, btnVoltarCompra});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReferenciaActionPerformed

    private void txtSuperficieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuperficieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuperficieActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            // Obter a data do campo de texto
            String dataString = txtDataPedido.getText().trim();

            // Validar e converter a data
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false); // Para garantir que a data seja válida
            java.util.Date data = sdf.parse(dataString);
            long dataTimestamp = data.getTime(); // Converte para timestamp

            // Obter os outros dados do produto
            String codigo = txtReferencia.getText().trim();
            String produto = txtProduto.getText().trim();
            String superficie = txtSuperficie.getText().trim();
            String colecao = txtColecao.getText().trim();
            String formato = txtFormato.getText().trim();
            String localUso = txtLocalUso.getText().trim();

            double m2Pallet = Double.parseDouble(txtM2Pallet.getText().trim().replace(",", "."));
            double kgM2 = Double.parseDouble(txtKgM2.getText().trim().replace(",", "."));
            double m2Caixa = Double.parseDouble(txtM2Caixa.getText().trim().replace(",", "."));
            int pcsCaixa = Integer.parseInt(txtPcsCaixa.getText().trim());
            double valorPaletizado = Double.parseDouble(txtValorPalletizado.getText().trim().replace("R$", "").replace(",", "."));

            // Cria o objeto Produto
            Produto produtoObj = new Produto(codigo, produto, superficie, colecao, formato, localUso, m2Pallet, kgM2, m2Caixa, pcsCaixa, valorPaletizado);

            // Salva no banco usando o id do pedido
            ProdutoDAO produtoDAO = new ProdutoDAO();
            produtoDAO.salvarProduto(produtoObj, idPedido);

            // Atualiza a tabela do pedido
            carregarProdutosNaTabela();

            // Limpa os campos
            txtReferencia.setText("");
            txtProduto.setText("");
            txtSuperficie.setText("");
            txtColecao.setText("");
            txtFormato.setText("");
            txtLocalUso.setText("");
            txtM2Pallet.setText("");
            txtKgM2.setText("");
            txtM2Caixa.setText("");
            txtPcsCaixa.setText("");
            txtValorPalletizado.setText("");
            txtDataPedido.setText(""); // Limpa o campo de data

            JOptionPane.showMessageDialog(this, "Produto adicionado ao pedido.");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao converter a data. Formato esperado: dd/MM/yyyy.");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao converter valores numéricos.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar produto: " + ex.getMessage());
            ex.printStackTrace();
        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCompraActionPerformed
        new TelaPedidosCliente(idCliente).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarCompraActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        try {
            int row = tabelaProdutos.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
                return;
            }

            // Pegando a referência da coluna 0
            Object valorCelula = tabelaProdutos.getValueAt(row, 0);
            if (valorCelula == null) {
                JOptionPane.showMessageDialog(null, "Referência não encontrada na linha selecionada.");
                return;
            }

            String referencia = valorCelula.toString();

            int confirm = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir este produto?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                ProdutoDAO produtoDAO = new ProdutoDAO();
                produtoDAO.excluirProduto(referencia, idPedido);

                carregarProdutosNaTabela(); // Atualiza a lista
                JOptionPane.showMessageDialog(null, "Produto excluído com sucesso.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir o produto: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            // Obtém a referência do campo de texto
            String referencia = txtReferencia.getText().trim();

            // Verifica se a referência não está vazia
            if (referencia.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, insira uma referência válida.");
                return;
            }

            // Cria uma instância do ProdutoDAO
            ProdutoDAO produtoDAO = new ProdutoDAO();

            // Busca o produto pela referência
            Produto p = produtoDAO.buscarPorReferencia(referencia);

            // Verifica se o produto foi encontrado
            if (p != null) {
                // Preenche os campos de texto com os dados do produto
                txtProduto.setText(p.getProduto());
                txtSuperficie.setText(p.getSuperficie());
                txtColecao.setText(p.getColecao());
                txtFormato.setText(p.getFormato());
                txtLocalUso.setText(p.getLocalUso());

                txtM2Pallet.setText(String.format("%.2f", p.getM2Pallet()));
                txtKgM2.setText(String.format("%.2f", p.getKgM2()));
                txtM2Caixa.setText(String.format("%.2f", p.getM2Caixa()));
                txtPcsCaixa.setText(String.valueOf(p.getPcsCaixa()));
                txtValorPalletizado.setText(String.format("%.2f", p.getValorPalletizado()));
            } else {
                // Se o produto não for encontrado, exibe uma mensagem
                JOptionPane.showMessageDialog(null, "Produto não encontrado!");
            }
        } catch (Exception ex) {
            // Em caso de erro, exibe a exceção
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto: " + ex.getMessage());
            ex.printStackTrace();
        }

                }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtLocalUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalUsoActionPerformed

    private void txtColecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColecaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColecaoActionPerformed

    private void txtM2CaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM2CaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM2CaixaActionPerformed

    private void txtM2PalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtM2PalletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtM2PalletActionPerformed

    private void txtPcsCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPcsCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPcsCaixaActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
           if (idPedido != -1) { // Verifica se o pedido foi criado com sucesso
    try {
        PedidoDAO pedidoDAO = new PedidoDAO();

        // Buscar o pedido com base no ID
        Pedido pedido = pedidoDAO
                .listarPedidosPorCliente(idCliente)
                .stream()
                .filter(p -> p.getIdPedido() == idPedido)
                .findFirst()
                .orElse(null);

        if (pedido != null) {
            // Exibe os dados do pedido nos campos correspondentes
            txtReferencia.setText(String.valueOf(pedido.getIdPedido()));
            txtDataPedido.setText(new SimpleDateFormat("dd/MM/yyyy").format(pedido.getDataPedido()));
            

            // Atualiza a tabela com os produtos deste pedido
            carregarProdutosNaTabela();
            JOptionPane.showMessageDialog(this, "Pedido Finalizado");
        } else {
            JOptionPane.showMessageDialog(this, "Erro: Pedido não encontrado.");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erro ao acessar o banco de dados: " + ex.getMessage());
        ex.printStackTrace();
    }
} else {
    JOptionPane.showMessageDialog(this, "Nenhum pedido foi criado. Verifique os dados.");
}


    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComprasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        int idCliente = 123; // ID do cliente
        // Use apenas o idCliente para criar a tela de compras
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComprasCliente(idCliente).setVisible(true); // Chama o construtor correto
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTextField txtColecao;
    private javax.swing.JTextField txtDataPedido;
    private javax.swing.JTextField txtFormato;
    private javax.swing.JTextField txtKgM2;
    private javax.swing.JTextField txtLocalUso;
    private javax.swing.JTextField txtM2Caixa;
    private javax.swing.JTextField txtM2Pallet;
    private javax.swing.JTextField txtPcsCaixa;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtSuperficie;
    private javax.swing.JTextField txtValorPalletizado;
    // End of variables declaration//GEN-END:variables

}
